// Code generated by "github.com/azr/generators/recycler -type=T -size 42 -template freelist.gotpl -output t_freelist.go"; DO NOT EDIT

package examples

//NewTFreeList instantiates a freelist of T
//TFreeList will be used to temporary store T objects
//for further usage and therefore save the memory
//allocation and garbage collection overhead.
//
//A TFreeList references at most 42 T objects
//in a chan.
//This prevents garbage collection for them
func NewTFreeList() *TFreeList {
	return &TFreeList{
		c: make(chan *T, 42),
	}
}

type TFreeList struct {
	c chan *T
}

func (p TFreeList) Get() *T {
	select {
	default:
		return new(T)
	case t := <-p.c:
		return t
	}
}

func (p TFreeList) Put(t *T) {
	select {
	default:
		//no more room
	case p.c <- t:
	}
}
