// Code generated by "varhandler -func Import"; DO NOT EDIT

package main

import "net/http"
import z "github.com/azr/generators/varhandler/examples/z"

func ImportHandler(w http.ResponseWriter, r *http.Request) {
	var err error

	param0, err := z.HTTPZ(r)
	if err != nil {
		HandleHTTPErrorWithDefaultStatus(w, r, http.StatusBadRequest, err)
		return
	}

	err = Import(param0)
	if err != nil {
		HandleHTTPErrorWithDefaultStatus(w, r, http.StatusInternalServerError, err)
		return
	}

}
