// Code generated by "varhandler -func Simple"; DO NOT EDIT

package main

import "net/http"

func SimpleHandler(w http.ResponseWriter, r *http.Request) {
	var err error

	param0, err := HTTPX(r)
	if err != nil {
		HandleHTTPErrorWithDefaultStatus(w, r, http.StatusBadRequest, err)
		return
	}

	param1, err := HTTPY(r)
	if err != nil {
		HandleHTTPErrorWithDefaultStatus(w, r, http.StatusBadRequest, err)
		return
	}

	param2, err := HTTPZ(r)
	if err != nil {
		HandleHTTPErrorWithDefaultStatus(w, r, http.StatusBadRequest, err)
		return
	}

	err = Simple(param0, param1, param2)
	if err != nil {
		HandleHTTPErrorWithDefaultStatus(w, r, http.StatusInternalServerError, err)
		return
	}

}
