// Code generated by "pooler -type=T"; DO NOT EDIT

package examples

import "sync"

type TPool struct {
	sync.Pool
}

func NewTPool() *TPool {
	return &TPool{
		sync.Pool{
			New: func() interface{} {
				return new(T)
			},
		},
	}
}

func (p TPool) Get() *T {
	return p.Pool.Get().(*T)
}

func (pp TPool) Put(p *T) {
	pp.Pool.Put(p)
}
